AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  music-converter

  Sample SAM Template for music-converter

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  MelodyAPI:
    Type: AWS::Serverless::Api # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      StageName: dev
      DefinitionUri: doc/swagger.yaml
  MusicConverterFunctionPermission: 
    Type: AWS::Lambda::Permission # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref MusicConverterFunction
      Principal: apigateway.amazonaws.com
  MusicConverterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      #MinimumCompressionSize: 10485760
      CodeUri: music_converter/upload_movie/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
  MusicConverterBucket:
    Type: AWS::S3::Bucket # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      BucketName: music-converter-bucket

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MusicConverterFunction:
    Description: "music converter Lambda Function ARN"
    Value: !GetAtt MusicConverterFunction.Arn
  MusicConverterFunctionIamRole:
    Description: "Implicit IAM Role created for music converter function"
    Value: !GetAtt MusicConverterFunctionRole.Arn
